export const FACES_MERGE_REQUEST = '@faces/FACES_MERGE_REQUEST';
export const FACES_MERGE_SUCCESS = '@faces/FACES_MERGE_SUCCESS';
export const FACES_MERGE_FAILURE = '@faces/FACES_MERGE_FAILURE';

export const FACES_MERGE_PROGRESS = '@faces/FACES_MERGE_PROGRESS';

export const FACES_SAVE_CONFIGS_REQUEST = '@faces/FACES_SAVE_CONFIGS_REQUEST';
export const FACES_SAVE_CONFIGS_SUCCESS = '@faces/FACES_SAVE_CONFIGS_SUCCESS';
export const FACES_SAVE_CONFIGS_FAILURE = '@faces/FACES_SAVE_CONFIGS_FAILURE';

export const FACES_GET_HISTORY_REQUEST = '@faces/FACES_GET_HISTORY_REQUEST';
export const FACES_GET_HISTORY_SUCCESS = '@faces/FACES_GET_HISTORY_SUCCESS';
export const FACES_GET_HISTORY_FAILURE = '@faces/FACES_GET_HISTORY_FAILURE';

export const FACES_GET_RESULT_REQUEST = '@faces/FACES_GET_RESULT_REQUEST';
export const FACES_GET_RESULT_SUCCESS = '@faces/FACES_GET_RESULT_SUCCESS';
export const FACES_GET_RESULT_FAILURE = '@faces/FACES_GET_RESULT_FAILURE';

export const FACES_RESET = '@faces/FACES_RESET';
